# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      force: true

spring:
  security:
    user:
      name: admin
      password: 123456
    jwt:
      key: zxcvbn
      expire: 7
