# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      force: true

spring:
  security:
    user:
      name: admin
      password: 123456
    jwt:
      key: zxcvbn
      expire: 7

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/login_jwt?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1900461953@qq.com
    password: adywhuyakoqlbiic
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
